Insert hours component
software-bastards/charlies-bastards-employee-dashboard pull request #6
Opened 2020-04-22 09:35 UTC by legyta

2020-04-23 08:06 UTC, reMRKableDev requested changes
@legyta Good job on the code in ```insert.js``` 👍 
This PR came with a lot of commits (some of which aren't just yours), I've added some comments in the files. Check it out and revise the changes. 

@seymonyu I think I've covered some of yours in here as well, right?

2020-04-23 08:06 UTC, reMRKableDev commented on client/src/App.js
> +/* import { withRouter } from "react-router-dom";
I suggest removing the commented ```imports``` that is not being used in this file. This way you keep the code that is in the ```master``` branch clean

2020-04-23 08:06 UTC, reMRKableDev commented on client/src/HOC/__test__/IsAuthorized.test.js
> +/* const setup = (props={})=>{
Add some tests for the HOC component, otherwise, this can affect the code coverage set on ```master```. 

A tip is to have your test do the following:

1. Create a mock store with the property that the HOC needs to map to. In your case, it would be the ```authorization.token ```
2. Create a component that the Auth renders when the user is authenticated.
3. Write assertions that checks if it returns(or renders) something 

__This is just an example of an assertion you could make__
```javascript
expect(receivedComponent).not.toBe(null) || expect(receivedComponent).toBe(null) 
```

This goes through all that I've explained above with an example, it can help when writing your test: https://dev.to/papaponmx/unit-testing-hoc-connected-components-2d8h

2020-04-23 08:06 UTC, reMRKableDev commented on client/src/containers/dashboard/Dashboard.js
> +import React, { useState, useEffect } from "react";
It doesn't look like the commented lines are being used. They may come into use later, but when making PRs, try and have the code as clean as possible

2020-04-23 08:06 UTC, reMRKableDev commented on client/src/containers/login/Login.js
> +   * @function onSuhmit
A typo here, I think you meant```@function onSubmit```

2020-04-23 08:06 UTC, reMRKableDev commented on server/database/configurationSequelize.js
> +  db.account /* , {foreignKey: 'id', targetKey: 'upload_id'} */
Not sure if this is needed here if it's not being used ```{foreignKey: 'id', targetKey: 'upload_id'}```

2020-04-23 08:06 UTC, reMRKableDev commented on server/routes/insert.js
> +//need to add jwt token
Looks like jwt was added, this comment can be removed

2020-04-27 15:28 UTC, zonakusu reviewed
Is this PR meant to push to master or develop? I see changes from Ligia in here which I also see in her PR to develop. I'm a bit confused 🙈

2020-04-27 15:28 UTC, zonakusu commented on client/coverage/clover.xml
> +<?xml version="1.0" encoding="UTF-8"?>
We can also gitignore all coverage files :) Makes repo a bit cleaner

2020-05-01 13:30 UTC, closed without merging